<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="LoginSuite" duration-ms="62269" started-at="2016-02-29T21:07:35Z" finished-at="2016-02-29T21:08:37Z">
    <groups>
    </groups>
    <test name="LoginTest" duration-ms="62269" started-at="2016-02-29T21:07:35Z" finished-at="2016-02-29T21:08:37Z">
      <class name="test.ui.LoginPageTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:test.ui.LoginPageTest@68837a77]" name="beforeSuite" is-config="true" duration-ms="5752" started-at="2016-02-29T13:07:29Z" finished-at="2016-02-29T13:07:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="init(java.lang.String, java.lang.String)[pri:0, instance:test.ui.LoginPageTest@68837a77]" name="init" is-config="true" duration-ms="1" started-at="2016-02-29T13:07:35Z" finished-at="2016-02-29T13:07:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[PHPSESSID]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[login]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="testLogin(java.lang.String, java.lang.String)[pri:1, instance:test.ui.LoginPageTest@68837a77]" name="testLogin" duration-ms="61860" started-at="2016-02-29T13:07:35Z" data-provider="users-data" finished-at="2016-02-29T13:08:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[raghava2706@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[training]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at test.ui.LoginPageTest.testLogin(LoginPageTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="SKIP" signature="testLogout()[pri:0, instance:test.ui.LoginPageTest@68837a77]" name="testLogout" duration-ms="0" started-at="2016-02-29T13:08:37Z" depends-on-methods="test.ui.LoginPageTest.testLogin" finished-at="2016-02-29T13:08:37Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LoginPageTest.testLogout()[pri:0, instance:test.ui.LoginPageTest@68837a77] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LoginPageTest.testLogout()[pri:0, instance:test.ui.LoginPageTest@68837a77] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:112)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:205)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:176)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogout -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:test.ui.LoginPageTest@68837a77]" name="afterSuite" is-config="true" duration-ms="70" started-at="2016-02-29T13:08:37Z" finished-at="2016-02-29T13:08:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- test.ui.LoginPageTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- LoginSuite -->
</testng-results>
